spring.application.name=metrica-service
server.port=8087
spring.profiles.active=h2

pedido.service.url=${PEDIDO_SERVICE_URL:http://localhost:8081}
cliente.service.url=${CLIENTE_SERVICE_URL:http://localhost:8082}

spring.cloud.openfeign.okhttp.enabled=true
