@echo off
echo Iniciando microservicios...

echo Levantando Cliente Service (8082)...
start "Cliente Service" cmd /k ".\mvnw.cmd spring-boot:run -pl cliente-service"

echo Esperando 5 segundos para que Cliente Service inicialice...
timeout /t 5 /nobreak >nul

echo Levantando Pedido Service (8081)...
start "Pedido Service" cmd /k ".\mvnw.cmd spring-boot:run -pl pedido-service"

echo Levantando Fabricacion Service (8086)...
start "fabricacion-service" cmd /k "mvnw.cmd spring-boot:run -pl fabricacion-service"

echo Arrancando producto-service (Puerto 8083)...
start "producto-service" cmd /k "mvnw.cmd spring-boot:run -pl producto-service"

echo Arrancando despacho-service (Puerto 8084)...
start "despacho-service" cmd /k "mvnw.cmd spring-boot:run -pl despacho-service"

echo Arrancando estado-service (Puerto 8085)...
start "estado-service" cmd /k "mvnw.cmd spring-boot:run -pl estado-service"

echo Arrancando metrica-service (Puerto 8087)...
start "metrica-service" cmd /k "mvnw.cmd spring-boot:run -pl metrica-service"

echo Arrancando transportista-service (Puerto 8088)...
start "transportista-service" cmd /k "mvnw.cmd spring-boot:run -pl transportista-service"

echo Todos los servicios han sido lanzados.
