distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/4.0.0-rc-5/apache-maven-4.0.0-rc-5-bin.zip
distributionBase=MAVEN_USER_HOME
distributionPath=.m2/wrapper/dists
zipStoreBase=MAVEN_USER_HOME
zipStorePath=.m2/wrapper/dists
networkTimeout=10000
