spring.application.name=despacho-service
server.port=8084
spring.profiles.active=h2

pedido.service.url=http://localhost:8081
services.transportista-service.url=http://localhost:8088

# Habilitar OkHttp en Feign (igual que los otros módulos)
spring.cloud.openfeign.okhttp.enabled=true
