spring.datasource.url=jdbc:postgresql://TU_HOST_SUPABASE:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=TU_PASSWORD_SUPABASE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
