spring.application.name=api-pedidos
spring.profiles.default=h2
spring.jpa.open-in-view=false
services.cliente-service.url=${CLIENTE_SERVICE_URL:http://localhost:8080}
services.producto-service.url=${PRODUCTO_SERVICE_URL:http://localhost:8081}
services.despacho-service.url=${DESPACHO_SERVICE_URL:http://localhost:8082}
