spring.application.name=metrica-service
server.port=8087
spring.profiles.active=h2

pedido.service.url=${PEDIDO_SERVICE_URL:http://localhost:8081}
cliente.service.url=${CLIENTE_SERVICE_URL:http://localhost:8082}

spring.cloud.openfeign.okhttp.enabled=true

# JWT Auth
jwt.secret=dHVjbGF2ZXNlY3JldGFkZWJlc2VybXV5bGFyZ2FwYXJhcXVlc2VhcnNlZ3VyYQ==
jwt.expiration-ms=86400000

