package cl.apipedidos.cliente.gui;

import cl.apipedidos.http.client.ClienteApiClient;
import cl.apipedidos.http.client.UbicacionApiClient;
import cl.apipedidos.http.dto.ClienteCreateRequestDTO;
import cl.apipedidos.http.dto.ClienteResponseDTO;
import cl.apipedidos.http.dto.ComunaResponseDTO;
import cl.apipedidos.http.dto.RegionResponseDTO;
import cl.apipedidos.http.error.HttpClientException;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.awt.*;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import javax.swing.*;

public class RegistroUsuarios extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName());
    private static final String REGION_PLACEHOLDER = "--Seleccione una región--";
    private static final String COMUNA_PLACEHOLDER = "--Seleccione una comuna--";

    private final ClienteApiClient clienteApiClient;
    private final UbicacionApiClient ubicacionApiClient;

    /**
     * Creates new form RegistroUsuarios
     */
    public RegistroUsuarios() {
        this(createDefaultClienteApiClient(), createDefaultUbicacionApiClient());
    }

    public RegistroUsuarios(ClienteApiClient clienteApiClient, UbicacionApiClient ubicacionApiClient) {
        this.clienteApiClient = Objects.requireNonNull(clienteApiClient, "clienteApiClient");
        this.ubicacionApiClient = Objects.requireNonNull(ubicacionApiClient, "ubicacionApiClient");
        initComponents();
        configurarAspectoCampos();
        centrarVentana();
        inicializarCombos();
        configurarEventos();
        cargarRegiones();
    }

    private static ClienteApiClient createDefaultClienteApiClient() {
        return new ClienteApiClient(createDefaultObjectMapper(), resolveBaseUrl());
    }

    private static UbicacionApiClient createDefaultUbicacionApiClient() {
        return new UbicacionApiClient(createDefaultObjectMapper(), resolveBaseUrl());
    }

    private static ObjectMapper createDefaultObjectMapper() {
        return new ObjectMapper().findAndRegisterModules();
    }

    private static String resolveBaseUrl() {
        return System.getProperty("app.http.base-url", "http://localhost:8080");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formularioClLbl = new JLabel();
        nombreClLbl = new JLabel();
        rutClLbl = new JLabel();
        emailClLbl = new JLabel();
        telefonoClLbl = new JLabel();
        direccionClLbl = new JLabel();
        comunaClLbl = new JLabel();
        regionClLbl = new JLabel();
        nombreClTxt = new JTextField();
        rutClTxt = new JTextField();
        emailClTxt = new JTextField();
        telefonoClTxt = new JTextField();
        direccionClTxt = new JTextField();
        rutDVClTxt = new JTextField();
        registroClBtn = new JButton();
        comunaClComboBox = new JComboBox<>();
        regionClComboBox = new JComboBox<>();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        formularioClLbl.setText("Registrar Nuevo Cliente");

        nombreClLbl.setText("Nombre:");

        rutClLbl.setText("RUT:");

        emailClLbl.setText("Email:");

        telefonoClLbl.setText("Teléfono:");

        direccionClLbl.setText("Dirección:");

        comunaClLbl.setText("Comuna:");

        regionClLbl.setText("Región:");

        registroClBtn.setText("Registrar");

        formularioClLbl.setHorizontalAlignment(SwingConstants.CENTER);

        comunaClComboBox.setModel(new DefaultComboBoxModel<>(new SelectableOption[] { }));

        regionClComboBox.setModel(new DefaultComboBoxModel<>(new SelectableOption[] { }));

        nombreClTxt.setColumns(24);
        rutClTxt.setColumns(12);
        rutDVClTxt.setColumns(2);
        emailClTxt.setColumns(24);
        telefonoClTxt.setColumns(24);
        direccionClTxt.setColumns(24);

        nombreClTxt.setCaretColor(Color.BLACK);
        rutClTxt.setCaretColor(Color.BLACK);
        rutDVClTxt.setCaretColor(Color.BLACK);
        emailClTxt.setCaretColor(Color.BLACK);
        telefonoClTxt.setCaretColor(Color.BLACK);
        direccionClTxt.setCaretColor(Color.BLACK);

        JPanel contentPanel = new JPanel(new GridBagLayout());
        contentPanel.setBorder(BorderFactory.createEmptyBorder(20, 28, 20, 28));
        setContentPane(contentPanel);

        GridBagConstraints constraints = new GridBagConstraints();
        constraints.insets = new Insets(5, 8, 5, 8);
        constraints.anchor = GridBagConstraints.WEST;

        constraints.gridx = 0;
        constraints.gridy = 0;
        constraints.gridwidth = 3;
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.weightx = 1.0;
        constraints.anchor = GridBagConstraints.CENTER;
        constraints.insets = new Insets(5, 8, 16, 8);
        contentPanel.add(formularioClLbl, constraints);

        constraints.gridwidth = 1;
        constraints.weightx = 0.0;
        constraints.fill = GridBagConstraints.NONE;
        constraints.anchor = GridBagConstraints.WEST;
        constraints.insets = new Insets(5, 8, 5, 8);

        constraints.gridx = 0;
        constraints.gridy = 1;
        contentPanel.add(nombreClLbl, constraints);

        constraints.gridx = 1;
        constraints.gridwidth = 2;
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.weightx = 1.0;
        contentPanel.add(nombreClTxt, constraints);

        constraints.gridwidth = 1;
        constraints.weightx = 0.0;
        constraints.fill = GridBagConstraints.NONE;

        constraints.gridx = 0;
        constraints.gridy = 2;
        contentPanel.add(rutClLbl, constraints);

        constraints.gridx = 1;
        constraints.gridwidth = 1;
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.weightx = 1.0;
        contentPanel.add(rutClTxt, constraints);

        constraints.gridx = 2;
        constraints.weightx = 0.0;
        constraints.fill = GridBagConstraints.NONE;
        contentPanel.add(rutDVClTxt, constraints);

        constraints.gridx = 0;
        constraints.gridy = 3;
        contentPanel.add(emailClLbl, constraints);

        constraints.gridx = 1;
        constraints.gridwidth = 2;
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.weightx = 1.0;
        contentPanel.add(emailClTxt, constraints);

        constraints.gridwidth = 1;
        constraints.weightx = 0.0;
        constraints.fill = GridBagConstraints.NONE;

        constraints.gridx = 0;
        constraints.gridy = 4;
        contentPanel.add(telefonoClLbl, constraints);

        constraints.gridx = 1;
        constraints.gridwidth = 2;
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.weightx = 1.0;
        contentPanel.add(telefonoClTxt, constraints);

        constraints.gridwidth = 1;
        constraints.weightx = 0.0;
        constraints.fill = GridBagConstraints.NONE;

        constraints.gridx = 0;
        constraints.gridy = 5;
        contentPanel.add(direccionClLbl, constraints);

        constraints.gridx = 1;
        constraints.gridwidth = 2;
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.weightx = 1.0;
        contentPanel.add(direccionClTxt, constraints);

        constraints.gridwidth = 1;
        constraints.weightx = 0.0;
        constraints.fill = GridBagConstraints.NONE;

        constraints.gridx = 0;
        constraints.gridy = 6;
        contentPanel.add(regionClLbl, constraints);

        constraints.gridx = 1;
        constraints.gridwidth = 2;
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.weightx = 1.0;
        contentPanel.add(regionClComboBox, constraints);

        constraints.gridwidth = 1;
        constraints.weightx = 0.0;
        constraints.fill = GridBagConstraints.NONE;

        constraints.gridx = 0;
        constraints.gridy = 7;
        contentPanel.add(comunaClLbl, constraints);

        constraints.gridx = 1;
        constraints.gridwidth = 2;
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.weightx = 1.0;
        contentPanel.add(comunaClComboBox, constraints);

        constraints.gridx = 0;
        constraints.gridy = 8;
        constraints.gridwidth = 3;
        constraints.fill = GridBagConstraints.NONE;
        constraints.anchor = GridBagConstraints.CENTER;
        constraints.weightx = 1.0;
        constraints.insets = new Insets(14, 8, 0, 8);
        contentPanel.add(registroClBtn, constraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> new RegistroUsuarios().setVisible(true));
    }

    private void inicializarCombos() {
        regionClComboBox.setModel(new DefaultComboBoxModel<>(new SelectableOption[] {
            new SelectableOption(null, REGION_PLACEHOLDER)
        }));
        comunaClComboBox.setModel(new DefaultComboBoxModel<>(new SelectableOption[] {
            new SelectableOption(null, COMUNA_PLACEHOLDER)
        }));
    }

    private void configurarEventos() {
        regionClComboBox.addActionListener(event -> actualizarComunasSegunRegionSeleccionada());
        registroClBtn.addActionListener(event -> registrarUsuario());
    }

    private void cargarRegiones() {
        new SwingWorker<List<RegionResponseDTO>, Void>() {
            @Override
            protected List<RegionResponseDTO> doInBackground() {
                return ubicacionApiClient.listarRegiones();
            }

            @Override
            protected void done() {
                try {
                    establecerRegiones(get());
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarErrorCarga("No fue posible cargar las regiones.", exception);
                } catch (ExecutionException exception) {
                    mostrarErrorCarga("No fue posible cargar las regiones.", exception.getCause());
                }
            }
        }.execute();
    }

    private void actualizarComunasSegunRegionSeleccionada() {
        SelectableOption regionSeleccionada = obtenerRegionSeleccionada();

        if (regionSeleccionada == null || regionSeleccionada.esPlaceholder()) {
            establecerComunasSoloPlaceholder();
            return;
        }

        cargarComunas(regionSeleccionada);
    }

    private void cargarComunas(SelectableOption regionSeleccionada) {
        new SwingWorker<List<ComunaResponseDTO>, Void>() {
            @Override
            protected List<ComunaResponseDTO> doInBackground() {
                return ubicacionApiClient.listarComunasPorRegion(regionSeleccionada.getValue());
            }

            @Override
            protected void done() {
                try {
                    establecerComunas(get());
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarErrorCarga("No fue posible cargar las comunas.", exception);
                    establecerComunasSoloPlaceholder();
                } catch (ExecutionException exception) {
                    mostrarErrorCarga("No fue posible cargar las comunas.", exception.getCause());
                    establecerComunasSoloPlaceholder();
                }
            }
        }.execute();
    }

    private void registrarUsuario() {
        try {
            ClienteCreateRequestDTO request = construirRequest();
            registroClBtn.setEnabled(false);

            new SwingWorker<ClienteResponseDTO, Void>() {
                @Override
                protected ClienteResponseDTO doInBackground() {
                    return clienteApiClient.crearCliente(request);
                }

                @Override
                protected void done() {
                    try {
                        ClienteResponseDTO response = get();
                        mostrarMensajeExito("Cliente registrado correctamente con ID " + response.idCliente() + ".");
                        limpiarFormulario();
                    } catch (InterruptedException exception) {
                        Thread.currentThread().interrupt();
                        mostrarErrorRegistro("No fue posible completar el registro.", exception);
                    } catch (ExecutionException exception) {
                        mostrarErrorRegistro("No fue posible completar el registro.", exception.getCause());
                    } finally {
                        registroClBtn.setEnabled(true);
                    }
                }
            }.execute();
        } catch (IllegalArgumentException exception) {
            mostrarMensajeError(exception.getMessage());
        }
    }

    private ClienteCreateRequestDTO construirRequest() {
        String nombre = nombreClTxt.getText() != null ? nombreClTxt.getText().trim() : "";
        String rutTexto = rutClTxt.getText() != null ? rutClTxt.getText().trim() : "";
        String dv = rutDVClTxt.getText() != null ? rutDVClTxt.getText().trim() : "";
        String email = emailClTxt.getText() != null ? emailClTxt.getText().trim() : "";
        String telefono = telefonoClTxt.getText() != null ? telefonoClTxt.getText().trim() : "";
        String direccion = direccionClTxt.getText() != null ? direccionClTxt.getText().trim() : "";

        if (nombre.isBlank()) {
            throw new IllegalArgumentException("El nombre es obligatorio.");
        }

        if (rutTexto.isBlank()) {
            throw new IllegalArgumentException("El RUT es obligatorio.");
        }

        long rut;

        try {
            rut = Long.parseLong(rutTexto);
        } catch (NumberFormatException exception) {
            throw new IllegalArgumentException("El RUT debe ingresarse solo con números, sin puntos ni guión.");
        }

        if (email.isBlank()) {
            throw new IllegalArgumentException("El email es obligatorio.");
        }

        if (telefono.isBlank()) {
            throw new IllegalArgumentException("El teléfono es obligatorio.");
        }

        if (direccion.isBlank()) {
            throw new IllegalArgumentException("La dirección es obligatoria.");
        }

        SelectableOption comunaSeleccionada = obtenerComunaSeleccionada();

        if (comunaSeleccionada == null || comunaSeleccionada.esPlaceholder()) {
            throw new IllegalArgumentException("Selecciona una comuna.");
        }

        return new ClienteCreateRequestDTO(
            nombre,
            rut,
            dv.toUpperCase(),
            direccion,
            email,
            telefono,
            comunaSeleccionada.getValue()
        );
    }

    private void establecerRegiones(List<RegionResponseDTO> regiones) {
        DefaultComboBoxModel<SelectableOption> model = new DefaultComboBoxModel<>();
        model.addElement(new SelectableOption(null, REGION_PLACEHOLDER));

        for (RegionResponseDTO region : regiones) {
            model.addElement(new SelectableOption(region.idRegion(), region.nombreRegion()));
        }

        regionClComboBox.setModel(model);
        regionClComboBox.setSelectedIndex(0);
        establecerComunasSoloPlaceholder();
    }

    private void establecerComunas(List<ComunaResponseDTO> comunas) {
        DefaultComboBoxModel<SelectableOption> model = new DefaultComboBoxModel<>();
        model.addElement(new SelectableOption(null, COMUNA_PLACEHOLDER));

        for (ComunaResponseDTO comuna : comunas) {
            model.addElement(new SelectableOption(comuna.nombreComuna(), comuna.nombreComuna()));
        }

        comunaClComboBox.setModel(model);
        comunaClComboBox.setSelectedIndex(0);
    }

    private void establecerComunasSoloPlaceholder() {
        DefaultComboBoxModel<SelectableOption> model = new DefaultComboBoxModel<>();
        model.addElement(new SelectableOption(null, COMUNA_PLACEHOLDER));
        comunaClComboBox.setModel(model);
        comunaClComboBox.setSelectedIndex(0);
    }

    private SelectableOption obtenerRegionSeleccionada() {
        return (SelectableOption) regionClComboBox.getSelectedItem();
    }

    private SelectableOption obtenerComunaSeleccionada() {
        return (SelectableOption) comunaClComboBox.getSelectedItem();
    }

    private void limpiarFormulario() {
        nombreClTxt.setText("");
        rutClTxt.setText("");
        rutDVClTxt.setText("");
        emailClTxt.setText("");
        telefonoClTxt.setText("");
        direccionClTxt.setText("");
        regionClComboBox.setSelectedIndex(0);
        establecerComunasSoloPlaceholder();
    }

    private void configurarAspectoCampos() {
        nombreClTxt.setPreferredSize(new Dimension(320, nombreClTxt.getPreferredSize().height));
        rutClTxt.setPreferredSize(new Dimension(200, rutClTxt.getPreferredSize().height));
        rutDVClTxt.setPreferredSize(new Dimension(40, rutDVClTxt.getPreferredSize().height));
        emailClTxt.setPreferredSize(new Dimension(320, emailClTxt.getPreferredSize().height));
        telefonoClTxt.setPreferredSize(new Dimension(320, telefonoClTxt.getPreferredSize().height));
        direccionClTxt.setPreferredSize(new Dimension(320, direccionClTxt.getPreferredSize().height));
        regionClComboBox.setPreferredSize(new Dimension(320, regionClComboBox.getPreferredSize().height));
        comunaClComboBox.setPreferredSize(new Dimension(320, comunaClComboBox.getPreferredSize().height));
        nombreClTxt.setCaretColor(Color.BLACK);
        rutClTxt.setCaretColor(Color.BLACK);
        rutDVClTxt.setCaretColor(Color.BLACK);
        emailClTxt.setCaretColor(Color.BLACK);
        telefonoClTxt.setCaretColor(Color.BLACK);
        direccionClTxt.setCaretColor(Color.BLACK);

        javax.swing.border.Border borde = BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(160, 160, 160), 1),
            BorderFactory.createEmptyBorder(3, 6, 3, 6)
        );

        nombreClTxt.setBorder(borde);
        rutClTxt.setBorder(borde);
        rutDVClTxt.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(160, 160, 160), 1),
            BorderFactory.createEmptyBorder(3, 4, 3, 4)
        ));
        emailClTxt.setBorder(borde);
        telefonoClTxt.setBorder(borde);
        direccionClTxt.setBorder(borde);
        setMinimumSize(new Dimension(540, 430));
        setResizable(false);
    }

    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = Math.max(0, (screenSize.width - getWidth()) / 2);
        int y = Math.max(0, (screenSize.height - getHeight()) / 2);
        setLocation(x, y);
    }

    private void mostrarErrorCarga(String mensaje, Throwable exception) {
        logger.log(Level.WARNING, mensaje, exception);
        mostrarMensajeError(construirMensajeDeError(mensaje, exception));
    }

    private void mostrarErrorRegistro(String mensaje, Throwable exception) {
        logger.log(Level.WARNING, mensaje, exception);
        mostrarMensajeError(construirMensajeDeError(mensaje, exception));
    }

    private String construirMensajeDeError(String mensajeBase, Throwable exception) {
        String detalle = traducirErrorHttp(exception);
        if (detalle == null || detalle.isBlank()) {
            return mensajeBase;
        }

        return mensajeBase + " " + detalle;
    }

    private String traducirErrorHttp(Throwable exception) {
        if (exception instanceof HttpClientException httpClientException) {
            if (httpClientException.getStatusCode() == -1) {
                return "Verifica que el backend Spring Boot esté en ejecución.";
            }

            return httpClientException.getMessage();
        }

        if (exception == null) {
            return "";
        }

        String message = exception.getMessage();
        return message != null ? message : "";
    }

    private void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
    }

    private void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error de validación", JOptionPane.ERROR_MESSAGE);
    }

    private static final class SelectableOption {

        private final String value;
        private final String displayText;

        private SelectableOption(String value, String displayText) {
            this.value = value;
            this.displayText = displayText;
        }

        private boolean esPlaceholder() {
            return value == null || value.isBlank();
        }

        private String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return displayText;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<SelectableOption> comunaClComboBox;
    private javax.swing.JLabel comunaClLbl;
    private javax.swing.JLabel direccionClLbl;
    private javax.swing.JTextField direccionClTxt;
    private javax.swing.JLabel emailClLbl;
    private javax.swing.JTextField emailClTxt;
    private javax.swing.JLabel formularioClLbl;
    private javax.swing.JLabel nombreClLbl;
    private javax.swing.JTextField nombreClTxt;
    private javax.swing.JComboBox<SelectableOption> regionClComboBox;
    private javax.swing.JLabel regionClLbl;
    private javax.swing.JButton registroClBtn;
    private javax.swing.JLabel rutClLbl;
    private javax.swing.JTextField rutClTxt;
    private javax.swing.JTextField rutDVClTxt;
    private javax.swing.JLabel telefonoClLbl;
    private javax.swing.JTextField telefonoClTxt;
    // End of variables declaration//GEN-END:variables
}
